[custom]
;解决DNS泄露，无分流群组
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=🚀 节点选择,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list

;AI线路手动切换
ruleset=🐸 AI网站,https://raw.githubusercontent.com/maxlixiang/openclash/refs/heads/main/AI.list
ruleset=📺 视频网站,https://raw.githubusercontent.com/maxlixiang/openclash/refs/heads/main/video.list






ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;新添加的去广告规则，似乎更完善一些，添加时间2026-Mar-8
ruleset=REJECT,https://raw.githubusercontent.com/maxlixiang/openclash/refs/heads/main/adreject.list


;自定义的直连规则，放到REJECT规则后面，可以更好的去除广告
ruleset=DIRECT,https://raw.githubusercontent.com/maxlixiang/openclash/refs/heads/main/Direct.list



ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🚀 节点选择,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🐸 AI网站`select`.*
custom_proxy_group=📺 视频网站`select`.*


enable_rule_generator=true
overwrite_original_rules=true
